### ISSUE TITLE
STRELKA deletions

### ISSUE THREAD

**Issue by jfwise** [bmannakee/mapexr#1]
I have used mapexr sucessfully on mutect output, but I have recently run in on a Strelka VCF output and for some reason I am only getting back results for the insertions. Any thoughts?

Bests
Jillian

**Comment by bmannakee** [comment]
HI Jillian,

I haven't run across that problem before. Would you be willing to email the vcf, or a portion of it? I am happy to test it out and make a fix.

Best,
Brian

**Comment by jfwise** [comment]
Hi Brian, 

That would be great if you could take a look, I guess it could also perhaps be an issue with Strelkas annotation and my bam/index file and the way it reports a deletion versus insertion?

Bests
Jillian
[MGH1504B.indels.txt](https://github.com/bmannakee/mapexr/files/2315769/MGH1504B.indels.txt)

**Comment by bmannakee** [comment]
Hi Jillian,

I will take a look. The process of finding Indels is pretty tough because it relies on Cigar strings in the bam file. It may also be that I am not handling the Strelka VCF format perfectly. I will take a look. Thanks for the file!

Brian

**Comment by bmannakee** [comment]
HI Jillian,

The variant loader is working correctly, finding both insertions and deletions. Can you tell me what aligner you used?

**Comment by jfwise** [comment]
I aligned with BWA-mem, sorted with samtools, marked-duplicates picard, filtered with gatk tools, used gatk for interval definition and local realignment

**Comment by bmannakee** [comment]
Great! I will let you know when I have a solution.

Thanks!

**Comment by jfwise** [comment]
Here was the mapexr output fo
[mapexr1504biopsyStrelka.txt](https://github.com/bmannakee/mapexr/files/2315872/mapexr1504biopsyStrelka.txt)
r that file. Also I used a hg19mm9 combined genome for the blastn

**Comment by bmannakee** [comment]
That is perfect. Thanks for all of the specifics

**Comment by jfwise** [comment]
I am sorry to waste your time Brian...I figured out the issue. It was on my end. The mapexr output reported each location one base pair different that my Strelka output. So when I tried to merge the files based on chr and location it was missed. Once again thank you for your quick response and I apologize

**Comment by bmannakee** [comment]
Hi Jillian,

No problem. I am glad it worked out. Let me know if you have any other problems.
